#!/bin/bash

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source _common.sh

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
final_path=$(ynh_app_setting_get "$app" final_path)

# Remove dependencies
ynh_remove_app_dependencies

# Remove sources
ynh_secure_remove $final_path

# Remove nginx configuration file
ynh_remove_nginx_config
