#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir/source"
fi

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# BUILD WITH NPM
#=================================================
ynh_script_progression --message="Building $app..." --weight=1

pushd "$install_dir/source"
    ynh_use_nodejs
    ynh_exec_warn_less ynh_exec_as "$app" env "$ynh_node_load_PATH" npm i
    ynh_exec_warn_less ynh_exec_as "$app" env "$ynh_node_load_PATH" npm run build
    ynh_secure_remove --file="node_modules"
popd

mv "$install_dir/source/dist/editor" "$install_dir/www"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
